Post comment directly from circleci
onCompare hook fails on node 10.15.3 due to a Buffer.from().toJSON() issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,12 +20,55 @@ orbs:
           - run:
               name: Upload build to user_interface build tracker server
               command: |
-                export PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/'  -f7)
                 export PATH_TO_BUILT_ASSETS=<<parameters.path>>
-                export BUNDLESIZE_COMMENT_LAMBDA_URL='https://tooling-lambdas.ctfl.now.sh/user_interface/bundlesizes'
                 npx bt-cli version
                 npx bt-cli -vv -c tools/build-tracker.config.js stat-artifacts
-                npx bt-cli -vv -c tools/build-tracker.config.js upload-build
+                npx bt-cli -c tools/build-tracker.config.js upload-build > uploadResult
+                # don't fail if upload fails as might happen when a job is re-run on the same commit
+                cat uploadResult | jq . || :
+          - post-comment/bundle-size:
+              buildUploadFile: 'uploadResult'
+
+  post-comment:
+    commands:
+      deployment:
+        description: 'Post deployment URLs to PR'
+        parameters:
+          env:
+            type: string
+            description: quirely or flinkly
+        steps:
+          - run:
+              name: Post deployment URL to GitHub
+              command: |
+                export PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/'  -f7)
+                export LAMBDA_URL="https://tooling-lambdas.ctfl.now.sh/user_interface/comments"
+                curl -i -X POST \
+                --data-binary "{\"issue\": ${PR_NUMBER:-\"\"}, \"branch\": \"${CIRCLE_BRANCH}\", \"commitSha\": \"${CIRCLE_SHA1}\", \"env\": \"<<parameters.env>>\"}" \
+                -H 'content-type: application/json' \
+                $LAMBDA_URL?token=$GITHUB_PAT_REPO_SCOPE_SQUIRELY || echo "Comment won't be posted to ${PR_NUMBER:-$CIRCLE_BRANCH}. Continuing anyway."
+
+      bundle-size:
+        description: 'Post bundle size comment to PR'
+        parameters:
+          buildUploadFile:
+            type: string
+            description: File containing data for the uploaded build
+        steps:
+          - run:
+              name: Post deployment URL to GitHub
+              command: |
+                export PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/'  -f7)
+                export LAMBDA_URL="https://tooling-lambdas.ctfl.now.sh/user_interface/bundlesizes"
+                export BUILD_TRACKER_MARKDOWN=$(cat <<parameters.buildUploadFile>> | jq .markdown | false || echo "")
+                export BUILD_TRACKER_URL='https://user-interface-build-tracker.herokuapp.com/'
+                # don't set COMMENT_MSG if there was no markdown as it probably means the build upload to our build tracker server failed
+                # not having this set will fail validation in the lambda that posts the comment which is what we want
+                export COMMENT_MSG=$([[ -n $BUILD_TRACKER_MARKDOWN ]] && echo "$BUILD_TRACKER_MARKDOWN<br />[Build tracker UI]($BUILD_TRACKER_URL)")
+                curl -i -X POST \
+                --data-binary "{\"issue\": ${PR_NUMBER:-\"\"}, \"message\": \"${COMMENT_MSG:-''}\"}" \
+                -H 'content-type: application/json' \
+                $LAMBDA_URL?token=$GITHUB_PAT_REPO_SCOPE_SQUIRELY || echo "Comment won't be posted to ${PR_NUMBER:-$CIRCLE_BRANCH}. Continuing anyway."
 
   deploy-assets:
     orbs:
@@ -60,28 +103,6 @@ orbs:
               from: <<parameters.path>>
               to: s3://<<parameters.bucket>>
               arguments: '--acl public-read --recursive'
-
-  post-comment:
-    commands:
-      to-pr:
-        description: 'Post deployment URL to PR that triggered the build as a comment'
-        parameters:
-          env:
-            type: string
-            description: quirely or flinkly
-          url:
-            type: string
-            description: url to POST comment data to
-            default: 'https://tooling-lambdas.ctfl.now.sh/user_interface/comments'
-        steps:
-          - run:
-              name: Post deployment URL to GitHub
-              command: |
-                export PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/'  -f7)
-                curl -i -X POST \
-                --data-binary "{\"issue\": ${PR_NUMBER:-\"\"}, \"branch\": \"${CIRCLE_BRANCH}\", \"commitSha\": \"${CIRCLE_SHA1}\", \"env\": \"<<parameters.env>>\"}" \
-                -H 'content-type: application/json' \
-                <<parameters.url>>?token=$GITHUB_PAT_REPO_SCOPE_SQUIRELY || echo "Comment won't be posted to ${PR_NUMBER:-$CIRCLE_BRANCH}. Continuing anyway."
 
   estivador:
     commands:
@@ -487,7 +508,7 @@ workflows:
           path: '~/workspace/output/files/staging'
           bucket: 'cf-staging-static-cdnorigin'
           post-steps:
-            - post-comment/to-pr:
+            - post-comment/deployment:
                 env: 'flinkly'
           requires:
             - build-and-push-image
